apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-datacenter
spec:
  template:
    metadata:
      name: countdown-datacenter
    spec:
      containers:
      - name: container-countdown-datacenter
        image: fedora:latest
        command: ["/bin/sh", "-c", "sleep 5"]
      restartPolicy: Never    
