apiVersion: batch/v1
kind: CronJob
metadata:
  name: devops-cronjob
spec:
  schedule: "*/9 * * * *" # Runs every 9 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-devops
            image: nginx:latest
            command: ["/bin/sh", "-c", "echo Welcome to xfusioncorp!"]
        restartPolicy: OnFailure