apiVersion: apps/v1
kind: Deployment
metadata:
  name: aps
  namespace: dev-stable   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aps
  template:               
    metadata:
      labels:             
        app: aps
    spec:
      containers:
      - name: tomee
        image: nginx      
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: aps-config
        - secretRef:
            name: aps-secret