#instructions args
FROM alpine:3.18

# using RUN to install packages
RUN apk add curl

#using WORKDIR to set the working directory
WORKDIR  /home/shiv_reddy/APS/Docker

RUN adduser -D shiv_reddy

#using USER to set the user
USER shiv_reddy

