apiversion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: my-app-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV_VAR_1
          value: "value1"   
        - name: ENV_VAR_2
          value: "value2"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"